### ISSUE TITLE
Jump from DRISHTI to Dhruv

### ISSUE THREAD

**Issue by aniket0112** [DRISHTI-SVNIT/Robocon#1]
Why does the repo jump from Dristhi/Robocon to Dhruv/Robocon? I think the final codes should be simply hosted directly by Drishti org so that there is no question of tracing the repo owner in case of any requirements in future. Also, add an year prefix to the repo to separate it from upcoming Robocon years. If you make a parent Robocon dir and make prefix folders inside for every year then say 10 years later the Robocon 2028 team will have to pull complete 10 year repo folder to work in this repo? @AtharvaKalsekar @himanshuk32 @Dhruv2012

**Comment by aniket0112** [comment]
https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

You can clone sub directories but it takes efforts. So either make sure you teach the people how to clone subdirectories or make no sub directories but host separate repos. Same concern with Miniprojects repo.

**Comment by AtharvaKalsekar** [comment]
Thank you sir for your suggestion..
The idea underlying such repo structure is keeping submodules

1. Maintaining a parent directory makes it simpler to organize the code. If
,in future , anybody needs to refer to a previous year's code then that
person won't be required to clone all the other repos as each repo being
independent of the other....means for example if it's 2021 now and if
anyone makes changes to 2018 or 2019 repo then that won't make it mandatory
for the person to clone it again.
Only one person ...i.e. the one who is the GitHub organizer of the current
year has all of the code on his physical device and only that person needs
to frequently update the submodules.. just a matter of few minutes.

2. The complete code remains with the drishti org as the github organizer
of the current year would handover (to the upcoming organizer) all the data.

3. Same goes for the mini-projects..
Moreover the mini-project foundation ideas being repeated every year would
make multiple repos in here having similar code.

Any more suggestions are welcome. If anything is being overlooked by us
then please let us know. Thank you.

**Comment by aniket0112** [comment]
So what I understood is there will be a personal Robocon dir hosted for the running year and once the competition is over, you will send over the project to a GitHub organizer who will check for structure, verify and add to the main Robocon directory hosted on Drishti org and create a new subdir for the new year?
Okay, that solves the problem of cloning huge repos in the future. Am I right in my interpretation? 
@AtharvaKalsekar

**Comment by AtharvaKalsekar** [comment]
Yes sir. Absolutely correct.

**Comment by aniket0112** [comment]
Okay then. Sounds cool. Closing in the issue
